spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        messaging-in:
          destination: messaging
          contentType: application/json
        messaging-out:
          destination: messaging
          contentType: application/json
